# FINVIZ_TICKERS = ['ticker', 'company_name', 'sector', 'industry', 'country', 'market_cap', 'pe', 'price',
#                   'price_chg', 'updated_dt']
FINVIZ_TICKERS = ['company_name', 'sector', 'industry', 'country', 'market_cap', 'pe', 'price',
                  'price_chg', 'updated_dt']

# FINVIZ_SCREENER = ['ticker', 'market_cap', 'pe', 'fwd_pe', 'peg', 'ps', 'pb', 'pc', 'pfcf', 'dividend',
#                                   'payout_ratio', 'eps', 'eps_this_y', 'eps_next_y', 'eps_past_5y', 'eps_next_5y',
#                                   'sales_past_5y', 'eps_q_q', 'sales_q_q', 'outstanding', 'float_shares',
#                                   'insider_own', 'insider_trans', 'inst_own', 'inst_trans', 'float_short',
#                                   'short_ratio', 'roa', 'roe',
#                                   'roi', 'curr_r', 'quick_r', 'ltdebt_eq', 'debt_eq', 'gross_m', 'oper_m', 'profit_m',
#                                   'perf_week', 'perf_month', 'perf_quart', 'perf_half', 'perf_year', 'perf_ytd',
#                                   'beta', 'atr', 'volatility_w', 'volatility_m', 'sma20', 'sma50', 'sma200',
#                                   '50d_high', '50d_low', '52w_high', '52w_low', 'rsi', 'from_open', 'gap', 'recom',
#                                   'avg_volume', 'rel_volume', 'price', 'price_chg', 'volume', 'earnings',
#                                   'target_price', 'ipo_date', 'updated_dt']
FINVIZ_SCREENER = ['market_cap', 'pe', 'fwd_pe', 'peg', 'ps', 'pb', 'pc', 'pfcf', 'dividend',
                                  'payout_ratio', 'eps', 'eps_this_y', 'eps_next_y', 'eps_past_5y', 'eps_next_5y',
                                  'sales_past_5y', 'eps_q_q', 'sales_q_q', 'outstanding', 'float_shares',
                                  'insider_own', 'insider_trans', 'inst_own', 'inst_trans', 'float_short',
                                  'short_ratio', 'roa', 'roe',
                                  'roi', 'curr_r', 'quick_r', 'ltdebt_eq', 'debt_eq', 'gross_m', 'oper_m', 'profit_m',
                                  'perf_week', 'perf_month', 'perf_quart', 'perf_half', 'perf_year', 'perf_ytd',
                                  'beta', 'atr', 'volatility_w', 'volatility_m', 'sma20', 'sma50', 'sma200',
                                  '50d_high', '50d_low', '52w_high', '52w_low', 'rsi', 'from_open', 'gap', 'recom',
                                  'avg_volume', 'rel_volume', 'price', 'price_chg', 'volume', 'earnings',
                                  'target_price', 'ipo_date', 'updated_dt']

COL_RENAMES = {'Ticker': 'ticker',
               'Company': 'company_name',
               'Sector': 'sector',
               'Industry': 'industry',
               'Country': 'country',
               'Market Cap': 'market_cap',
               'P/E': 'pe',
               'Fwd P/E': 'fwd_pe',
               'PEG': 'peg',
               'P/S': 'ps',
               'P/B': 'pb',
               'P/C': 'pc',
               'P/FCF': 'pfcf',
               'Dividend': 'dividend',
               'Payout Ratio': 'payout_ratio',
               'EPS': 'eps',
               'EPS this Y': 'eps_this_y',
               'EPS next Y': 'eps_next_y',
               'EPS past 5Y': 'eps_past_5y',
               'EPS next 5Y': 'eps_next_5y',
               'Sales past 5Y': 'sales_past_5y',
               'EPS Q/Q': 'eps_q_q',
               'Sales Q/Q': 'sales_q_q',
               'Outstanding': 'outstanding',
               'Float': 'float_shares',
               'Insider Own': 'insider_own',
               'Insider Trans': 'insider_trans',
               'Inst Own': 'inst_own',
               'Inst Trans': 'inst_trans',
               'Float Short': 'float_short',
               'Short Ratio': 'short_ratio',
               'ROA': 'roa',
               'ROE': 'roe',
               'ROI': 'roi',
               'Curr R': 'curr_r',
               'Quick R': 'quick_r',
               'LTDebt/Eq': 'ltdebt_eq',
               'Debt/Eq': 'debt_eq',
               'Gross M': 'gross_m',
               'Oper M': 'oper_m',
               'Profit M': 'profit_m',
               'Perf Week': 'perf_week',
               'Perf Month': 'perf_month',
               'Perf Quart': 'perf_quart',
               'Perf Half': 'perf_half',
               'Perf Year': 'perf_year',
               'Perf YTD': 'perf_ytd',
               'Beta': 'beta',
               'ATR': 'atr',
               'Volatility W': 'volatility_w',
               'Volatility M': 'volatility_m',
               'SMA20': 'sma20',
               'SMA50': 'sma50',
               'SMA200': 'sma200',
               '50D High': '50d_high',
               '50D Low': '50d_low',
               '52W High': '52w_high',
               '52W Low': '52w_low',
               'RSI': 'rsi',
               'from Open': 'from_open',
               'Gap': 'gap',
               'Recom': 'recom',
               'Avg Volume': 'avg_volume',
               'Rel Volume': 'rel_volume',
               'Price': 'price',
               'Change': 'price_chg',
               'Volume': 'volume',
               'Earnings': 'earnings',
               'Target Price': 'target_price',
               'IPO Date': 'ipo_date'}
